---
openapi: 3.0.0
servers: []
info:
  description: This is a reference API
  version: "1.0.0"
  title: Reference API
paths:
  /comments:
    post:
      summary: Create a new comment
      operationId: createComment
      description: Create a new comment
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
        description: The new comment

  /posts:
    get:
      summary: Gets all posts.
      operationId: getPosts
      description: |
        Gets all posts.
      responses:
        '200':
          description: All the posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCollection'
    post:
      summary: Creates a new post
      operationId: createPost
      description: It makes a new post authored by you, the current user
      responses:
        '201':
          description: Created post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
        description: The new post

  /posts/{id}:
    parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the post

    get:
      summary: Get a single post
      operationId: getPost
      description: Gets a single post
      responses:
        '200':
          description: The post identified by the ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a single post
      operationId: updatePost
      description: Updates a single post
      responses:
        '204':
          description: updated
        '403':
          description: You are not authorized to update this post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
    delete:
      summary: Delete a single post
      operationId: deletePost
      description: Deletes a single post
      responses:
        '200':
          description: The deleted resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '403':
          description: You are not authorized to delete this post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /posts/{id}/comments:
    get:
      summary: Get all comments for a post
      operationId: getPostComments
      description: Get all comments for a post
      responses:
        '200':
          description: Comments on the post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentCollection'
  /users/current:
    get:
      summary: Get the current user
      operationId: getCurrentUser
      description: Gets the current user
      responses:
        '200':
          description: The current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: Joan Baez
    Post:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 12345-abcdef-qwerty-foobar
        title:
          type: string
          example: Goto Considered Harmful
        body:
          type: string
          example: |
            To be or not to be, that is the question
        author:
          $ref: '#/components/schemas/User'
    PostRequest:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
    PostCollection:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
    Comment:
      type: object
      properties:
        body:
          type: string
          example: great job!
        id:
          type: string
        postId:
          type: string
          format: uuid
    CommentRequest:
      type: object
      properties:
        body:
          type: string
          example: love this post
        postId:
          type: string
          example: 123456-abcdef-qwerty-foobar
    CommentCollection:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Error:
      type: object
      properties:
        message:
          type: string
          example: Oops! That is not a valid id
        error:
          type: string
          example: Forbidden
        path:
          type: string
          example: /v1/posts